engines:
  checkstyle:
    enabled: true
    channel: "beta"
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  pmd:
    enabled: true
    channel: "beta"

ratings:
  paths:
  - "**.java"
  - "**.md"
